version: "3.9"

services:
  distribute:
    image: 172.16.1.131:5000/java-grpc-sample-distributed:${TAG}
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthy" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - java-grpc
  user:
    image: 172.16.1.131:5000/java-grpc-sample-user:${TAG}
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthy" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - java-grpc
  rest:
    image: 172.16.1.131:5000/java-grpc-sample-rest:${TAG}
    deploy:
      replicas: 2
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/healthy" ]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 40s
    ports:
      - "8080:8080"
    networks:
      - java-grpc
networks:
  java-grpc:
    name: java-grpc