version: "3.9"

services:
  distribute:
    image: lingen/java-grpc-sample-distributed:2
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
    networks:
      - java-grpc
  user:
    image: lingen/java-grpc-sample-user:2
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: dnsrr
    networks:
      - java-grpc
  rest:
    image: lingen/java-grpc-sample-rest:2
    deploy:
      replicas: 2

    ports:
      - "8080:8080"
    networks:
      - java-grpc
networks:
  java-grpc:
    name: java-grpc